import TodoAdd from '@/components/todoAdd';
import { TodoItemsContext } from '@/context/todo-items';
import Head from 'next/head';

export default function Home() {

  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <h1 className='mt-5 text-center'>TODO App with Context API</h1>
        <TodoItemsContext.Provider value={[]}>
          <TodoAdd />
        </TodoItemsContext.Provider>
      </main>
    </>
  );
};
